### ISSUE TITLE
Calling new methods on Older Versions error

### ISSUE THREAD

**Issue by iudragon** [mitchtabian/Spotify-Clone#2]
![screenshot_71](https://user-images.githubusercontent.com/45727449/50445898-bf5e7280-0937-11e9-967c-80be0a90673a.png)

in retrieving firestore data from playlist fragment video, i encountered this error while trying to run the app.
before it worked when I tested for category fragment.

**Comment by iudragon** [comment]
okay I suppressed this warning for now, but would it crash on older devices?

**Comment by mitchtabian** [comment]
You can delete those lines of code. They're not needed.

**Comment by mitchtabian** [comment]
You can delete those lines of code. They're not needed.

**Comment by iudragon** [comment]
> You can delete those lines of code. They're not needed.

okay! done.
