### ISSUE TITLE
Firestore database does not work when I use mine.

### ISSUE THREAD

**Issue by iudragon** [mitchtabian/Spotify-Clone#3]
App works when I use your google services json file. But not when mine, and this happens only during playlist fragment.

![screenshot_72](https://user-images.githubusercontent.com/45727449/50446559-73adc800-093b-11e9-8f66-3e9dd9ed3822.png)

I could share login details of firestore if screenshot is not enough.

**Comment by iudragon** [comment]
I forgot to change artist_id in mainactivity java file. in 17 th video spotify clone.

**Comment by mitchtabian** [comment]
Ok. So you're good now?

**Comment by iudragon** [comment]
> Ok. So you're good now?

yup. It was minor error on my part. code works fine

**Comment by mitchtabian** [comment]
Cool
